# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
    # riverpod_generatorの影響でg.dart末尾に不要な指定が付くので
    duplicate_ignore: ignore
  exclude:
    - lib/*_original.dart
    - lib/generated_*.dart
    - lib/main_global_object_key.dart
    - lib/firebase_options.dart
  plugins:
    - custom_lint
custom_lint:
  rules:
    avoid_public_notifier_properties: false
    missing_provider_scope: false
linter:
  rules:
    avoid_print: false
    sort_pub_dependencies: false
    unreachable_from_main: false
