# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
  exclude:
    - lib/*_original.dart
    - lib/generated_*.dart
    - lib/main_global_object_key.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    avoid_print: false
    sort_pub_dependencies: false
