// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJyv2G1Pz_6UO9QiRFxvpBH7kT01P8Dw',
    appId: '1:405166675189:web:3202f7016304165121a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    authDomain: 'mono-firebase.firebaseapp.com',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    measurementId: 'G-88BNG7KQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrk4rls6KWZOg1tWQyveuHWSHJD17NSfI',
    appId: '1:405166675189:android:30be9d2720600eae21a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-hfsH_AG8XsENm4upBsiiR61Zoy8MKo',
    appId: '1:405166675189:ios:7e464607ecdf977121a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    androidClientId: '405166675189-3gq9iprsmbi7nro6tm9njn61cslkm02n.apps.googleusercontent.com',
    iosClientId: '405166675189-qnf0jb8mbvt3avj0eatda89a60fnbobb.apps.googleusercontent.com',
    iosBundleId: 'com.mono0926.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-hfsH_AG8XsENm4upBsiiR61Zoy8MKo',
    appId: '1:405166675189:ios:594765df7731455621a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    androidClientId: '405166675189-3gq9iprsmbi7nro6tm9njn61cslkm02n.apps.googleusercontent.com',
    iosClientId: '405166675189-jnoej43uf1qlkhmcere297ev38pi0a3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApJyv2G1Pz_6UO9QiRFxvpBH7kT01P8Dw',
    appId: '1:405166675189:web:b5487269ca8289ee21a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    authDomain: 'mono-firebase.firebaseapp.com',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    measurementId: 'G-M7Y445W8LL',
  );
}
